blog/urls.py
from django.conf.urls import patterns, include, url
from .views import CategoryDetailView

urlpatterns = patterns('blog.views',
    url(r'^$', 'blog_main'),
    url(r'^/new-post$', 'new_post'),
    url(r'^/category/(?P<slug>[-\w]+)/?$', CategoryDetailView.as_view()),
    url(r'^/post/([-a-zA-Z0-9]+)/$', 'view_post'),
)

contactform/urls.py
from django.conf.urls import patterns, include, url
from .views import ContactFormView, ThanksView

urlpatterns = patterns('contactform.views',
    url(r'^/?$', ContactFormView.as_view()),
    url(r'^/thanks/?$', ThanksView.as_view()),
)

homepage/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'mainpage.views.main_page', name='home'),
    url(r'^about$', 'mainpage.views.about_page', name='about'),
    url(r'^login$', 'mainpage.views.login_page', name='login'),
    url(r'^logout$','mainpage.views.logout_page', name='logout'),

    url(r'^blog', include('blog.urls')),
    url(r'^contact', include('contactform.urls')),
    # url(r'^homepage/', include('homepage.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

blog/models.py
from django.utils import timezone as dtz

from django.db import models
from django.contrib.auth.models import User
import re

class Category(models.Model):
    name = models.CharField(max_length=512)
    link = models.CharField(max_length=512)

    @classmethod
    def get(cls, name):
        link = title_to_link(name)
        # create new category only if not present
        if Category.objects.filter(link=link).exists():
            category = Category.objects.get(link=link)
        else:
            category = Category(name=name)
            category.link = link
            category.save()
        return category

    def __str__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey(User)

    title = models.CharField(max_length=512)
    content = models.TextField()
    link = models.CharField(max_length=512)

    # these are stored as UTC
    submission_date = models.DateTimeField(auto_now_add=True)
    publication_date = models.DateTimeField(null=True,blank=True)
    publish = models.BooleanField(default=False)
    modification_date = models.DateTimeField(auto_now=True)

    tags = models.CharField(blank=True,max_length=512)
    # we allow posts without category
    category = models.ForeignKey(Category,null=True,blank=True)
    
    def save(self, *args, **kwargs):
        self.__fill_pub_date()
        super(Post, self).save(*args, **kwargs) # Call the "real" save() method.

    def __fill_pub_date(self):
        if self.publication_date is None and self.publish is True:
                self.publication_date = dtz.now()

def title_to_link(title):
    #to lowercase
    title = title.lower()
    # strip quotes
    title = re.sub(r"['\"]+","",title)
    # convert all characters except aplhanum to dashes
    title = re.sub(r"[^a-z0-9]+","-",title)
    # remove dashes at beginning and end
    title = re.sub(r"^-+|-+$","",title)
    # remove double dashes
    title = re.sub(r"--+","-",title)
    # continuous whitespace to dash
    title = re.sub(r"\s+","-",title)
    return title

contactform/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from django.core import validators


class TitleField(forms.CharField):
    default_error_messages = {
        'min_length': ('Title cannot be left empty.')
    }
    default_validators = [validators.MinLengthValidator(1)]


class AddNewPostForm(forms.Form):
    post_title = TitleField(max_length=512)
    post_content = forms.CharField(widget=forms.Textarea())
    post_publication_date = forms.DateTimeField(required=False)
    post_publish = forms.BooleanField(required=False)
    post_tags = forms.CharField(max_length=256,required=False)
    post_category = forms.CharField(max_length=256,required=False)

contactform/forms.py
from django import forms
from django.contrib.auth.models import User

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=256)
    message = forms.CharField(widget=forms.Textarea)
    contact_email = forms.EmailField(max_length=256)

    def send_email(self):
        contact = User.objects.get(username='contact')

        contact.email_user(
                self.cleaned_data['subject'],
                self.cleaned_data['message'],
                self.cleaned_data['contact_email'])

mainpage/forms.py
from django import forms
from django.core import validators

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.widgets.PasswordInput)

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
import django.utils.timezone as dtz
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from django.contrib.auth.decorators import login_required

from blog.forms import AddNewPostForm
from blog.models import Post, Category, title_to_link

def blog_main(request):
    posts = Post.objects.filter(publish=True,publication_date__lt=dtz.now())

    return render(request, 'blog/main.html', {'posts': posts})

@login_required
def new_post(request):
    if request.method == 'POST': 
        form = AddNewPostForm(request.POST) # A form bound to the POST data
        
        if form.is_valid(): # All validation rules pass
            Post.objects.create(
                    author=request.user,
                    title=form.cleaned_data['post_title'],
                    content=form.cleaned_data['post_content'],
                    link=title_to_link(form.cleaned_data['post_title']),
                    publication_date=form.cleaned_data['post_publication_date'],
                    publish=form.cleaned_data['post_publish'],
                    category=Category.get(form.cleaned_data['post_category']),
                    tags=form.cleaned_data['post_tags'],
            )
            return HttpResponseRedirect('/blog') # Redirect after POST
    else:
        form = AddNewPostForm() # An unbound form

    return render(request, 'blog/new-post.html', 
            {'form': form})

def view_post(request,post_link):
    post = Post.objects.get(link=post_link)

    return render(request, 'blog/view-post.html',{'post':post})

class CategoryDetailView(DetailView):
    model = Category
    context_object_name = 'category'
    slug_field = 'link'

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        context['posts'] = Category.objects.get(link=context['category'].link).post_set.all()
        return context

contactform/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.edit import FormView

from .forms import ContactForm
# Create your views here.
class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'contactform/contact.html'
    success_url = '/contact/thanks'

    def form_valid(self, form):
        form.send_email()
        return super(ContactFormView,self).form_valid(form)

class ThanksView(TemplateView):
    template_name = 'contactform/thanks.html'

mainpage/views.py
"""
Top level views for a homepage.
"""

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout

from mainpage.forms import LoginForm

def main_page(request):
    """
    Displays main page template.
    """
    return render(request,'mainpage/main.html')

def about_page(request):
    """
    Displays about page.
    """
    return render(request,'mainpage/about.html')

def login_page(request):
    """
    Displays a login form and processes it on submission.
    """
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        
        if login_form.is_valid():
            credentials = {
                    'username': login_form.cleaned_data['username'],
                    'password': login_form.cleaned_data['password']
            }
            user = authenticate(**credentials)
            if user is not None:
                login(request,user)
                return redirect('/blog')
    else:
    
        login_form = LoginForm()
    
    return render(request,'mainpage/login.html',{'form': login_form})

def logout_page(request):
    """
    A view for signing a user out..
    """
    logout(request)
    return redirect('/')

blog/templates/blog/category.html
<div id="categories">
    <h1>Categories</h1>

    <ul>
        {% for category in categories %}
            <li><a href="/blog/category/{{ category.link }}/">{{ category.name }}</a></li>
        {% endfor %}
    </ul>
</div>

blog/templates/blog/category_detail.html
{% extends 'blog/main.html' %}

{% block content %}
    <h1>{{ category.name }}</h1>

    {% for post in posts %}
        {% include 'blog/post.html' %}
    {% endfor %}
{% endblock %}

blog/templates/blog/main.html
{% extends 'mainpage/base.html' %}

{% load blog_tags %}

{% block title %}
    <Title>Blog</title>
{% endblock %}

{% block menu %}
    <ul class=menu>
        {% if user.is_authenticated %}
            <li><a href="/blog/new-post">New post</a></li>
        {% endif %}
    </ul>
{% endblock %}

{% block content %}
    {% category_list %}
    {% for post in posts %}
        {% include 'blog/post.html' %}
    {% endfor %}
{% endblock %}

blog/templates/blog/new-post.html
{% extends 'blog/main.html' %}

{% block title %}
    <Title>Add new post</title>
{% endblock %}

{% block content %}
    <h1>Add new post</h1>
    <form id="id_new_post" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input id="id_submit" type="submit" value="Submit" />
    </form>
{% endblock %}

blog/templates/blog/post.html
{% load mytags %}
{% load markdown_deux_tags %}

<a href="/blog/post/{{ post.link }}/"><h1>{{ post.title }}</h1></a>
<h6>published {{ post.publication_date | humandate }} by {{ post.author.first_name }} {{  post.author.last_name }} in {{ post.category }}</h6>
<div>{{ post.content | markdown }}</div>
<div>Tags: {{ post.tags }}</div>

blog/templates/blog/view-post.html
{% extends 'blog/main.html' %}

{% block title %}
    <Title>Blog</title>
{% endblock %}

{% block content %}
    {% include 'blog/post.html' %}
{% endblock %}

contactform/templates/contactform/contact.html
{% extends 'mainpage/main.html' %}

{% block title %}
    <title>Contact</title>
{% endblock %}

{% block content %}
    <h1>Contact me</h1>
    <form id="id_contact_form" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input id="id_submit" type="submit" value="Send"/>
    </form>
{% endblock %}

contactform/templates/contactform/thanks.html
{% extends 'mainpage/main.html' %}

{% block title %}
    <title>Thank you for your message</title>
{% endblock %}

mainpage/templates/base.html
<html>
    <head>
        {% block title %}
        {% endblock %}
    </head>
    <body>
        {% include 'mainmenu.html' %}
        {% block menu %}
        {% endblock %}
        {% block content %}
        {% endblock %}
    </body>
</html>

mainpage/templates/mainpage.html
{% extends 'base.html' %}

{% block title %}
    <title>Mainpage</title>
{% endblock %}

mainpage/templates/mainpage/about.html
{% extends 'mainpage/base.html' %}

{% block content %}
    <h1>About this page</h1>
{% endblock %}

mainpage/templates/mainpage/base.html
<html>
    <head>
        {% block title %}
        {% endblock %}
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static "mainpage/css/main.css" %}"/> 
    </head>
    <body>
        <div id="page">
            {# give us coloured box the width of a page #}
            <div class="blue-wrapper">
                {# header #}
                <div id="header" class="centered">
                    <h1 class="header">Pawel Mosakowski</h1>
                    <h4 class="subheader">On subject of summoning computer softwares and applications thereof.</h4>
                    <div id="login">
                        {% if user.is_authenticated %}
                            Hello, {{ user.username }}. <a href='/logout'>Log out</a>
                        {% else %}
                            Hello, visitor. <a href='/login'>Log in</a>
                        {% endif %}
                    </div>
                </div>
            </div>

            {# give us coloured box the width of a page #}
            <div class="blue-wrapper">
                {# menus #}
                <div id="main-menu" class="centered">
                    {# main menu #}
                    {% include 'mainpage/mainmenu.html' %}
                </div>
                <div id="page-menu" class="centered">
                    {# per page menu #}
                    {% block menu %}
                    {% endblock %}
                </div>
            </div>

            {# content #}
            <div id="content" class="centered">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

mainpage/templates/mainpage/login.html
{% extends 'mainpage/base.html' %}

{% block title %}
    <title>Login</title>
{% endblock %}

{% block content %}
    <form id="id_login" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input id="id_submit" type="submit" value="Login"/>
    </form>
{% endblock %}

mainpage/templates/mainpage/main.html
{% extends 'mainpage/base.html' %}

{% block title %}
    <title>Mainpage</title>
{% endblock %}

mainpage/templates/mainpage/mainmenu.html
<ul class="menu">
    <li><a href="/">Home</a></li>
    <li><a href="/blog">Blog</a></li>
    <li><a href="/about">About</a></li>
    <li><a href="/contact">Contact</a></li>
</ul>